### PR TITLE
Support memtest-auto #Danny

### PR DESCRIPTION
**Pull request by dalehamel**

### CODE REVIEW

**Comment by dalehamel** [comment]
@dwradcliffe

**Comment by dwradcliffe** [comment]
I think this needs to be rebased and refactored again

**Comment by dalehamel** [comment]
Yeah

**Comment by dturn** [comment]
I'm going to open a new PR for this after the refactor gets merged.

**Comment by dalehamel** [comment]
good idea

**Comment by dturn** [comment]
Closed for #15

**Pull request closed without merging**
