### PR TITLE
And memtest

### PR DESCRIPTION
**Pull request by dturn**
@dalehamel @dwradcliffe 

Post refactor version of https://github.com/Shopify/scrappystrap/pull/10

### CODE REVIEW

**Comment by dwradcliffe** [comment]
Seems a little weird for the bootstrap class to handle memtest...

**Comment by dturn** [comment]
Yeah, the bootstrap class is probably misnamed, maybe `ZygoteAction` ?

**Comment by dwradcliffe** [comment]
That's better

**Comment by dalehamel** [comment]
:+1: I did a :tophat: and it looks to work.

Only issue left I think is that genesis will automatically mark servers as unhealthy if a remote action takes more than 30 minutes, but memtest will almost always take more than 30 minutes.

**Comment by dalehamel** [comment]
Gunna merge, this is working.

**Pull request merged**
